using System;
using System.Collections.Generic;
using System.Configuration;
using Oracle.ManagedDataAccess.Client;

namespace DapolUltimate_MusicPlayer {
    public class OracleDbService {
        private readonly string _connectionString;

        public OracleDbService() {
            _connectionString = ConfigurationManager.ConnectionStrings["OracleDb"]?.ConnectionString;
        }

        private OracleConnection GetConnection() => new OracleConnection(_connectionString);

        public void EnsureTableExists() {
            using (var conn = GetConnection()) {
                conn.Open();
                using (var cmd = conn.CreateCommand()) {
                    cmd.CommandText = @"BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TRACKS (
        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        TITLE VARCHAR2(400),
        PATH VARCHAR2(1024),
        IS_YOUTUBE NUMBER(1),
        CREATED_AT TIMESTAMP
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;";
                    cmd.ExecuteNonQuery();
                }
            }
        }

        public List<TrackInfo> LoadTracks() {
            var list = new List<TrackInfo>();
            using (var conn = GetConnection()) {
                conn.Open();
                using (var cmd = conn.CreateCommand()) {
                    cmd.CommandText = "SELECT ID, TITLE, PATH, IS_YOUTUBE, CREATED_AT FROM TRACKS ORDER BY ID";
                    using (var reader = cmd.ExecuteReader()) {
                        while (reader.Read()) {
                            list.Add(new TrackInfo {
                                Id = reader.GetInt32(0),
                                Title = reader.IsDBNull(1) ? null : reader.GetString(1),
                                Path = reader.IsDBNull(2) ? null : reader.GetString(2),
                                IsYouTube = reader.GetInt32(3) == 1,
                                CreatedAt = reader.IsDBNull(4) ? DateTime.MinValue : reader.GetDateTime(4)
                            });
                        }
                    }
                }
            }
            return list;
        }

        public int AddTrack(TrackInfo track) {
            using (var conn = GetConnection()) {
                conn.Open();
                using (var cmd = conn.CreateCommand()) {
                    cmd.CommandText = @"INSERT INTO TRACKS (TITLE, PATH, IS_YOUTUBE, CREATED_AT)
VALUES (:title, :path, :isYT, :created) RETURNING ID INTO :id";
                    cmd.Parameters.Add(new OracleParameter("title", track.Title));
                    cmd.Parameters.Add(new OracleParameter("path", track.Path));
                    cmd.Parameters.Add(new OracleParameter("isYT", track.IsYouTube ? 1 : 0));
                    cmd.Parameters.Add(new OracleParameter("created", track.CreatedAt));
                    var idParam = new OracleParameter("id", OracleDbType.Int32, System.Data.ParameterDirection.Output);
                    cmd.Parameters.Add(idParam);
                    cmd.ExecuteNonQuery();
                    return Convert.ToInt32(idParam.Value.ToString());
                }
            }
        }

        public void DeleteTrack(int id) {
            using (var conn = GetConnection()) {
                conn.Open();
                using (var cmd = conn.CreateCommand()) {
                    cmd.CommandText = "DELETE FROM TRACKS WHERE ID = :id";
                    cmd.Parameters.Add(new OracleParameter("id", id));
                    cmd.ExecuteNonQuery();
                }
            }
        }
    }
}
